In [ ]:
"Py" == "Py"

True

In [2]:
"Py" != "Py"

False

In [5]:
1 == True

True

In [6]:
"1" == True

False

In [7]:
1 == True

True

In [8]:
1.0 == False

False

In [9]:
0 == False

True

In [10]:
"0" == False

False

In [11]:
2 >= 2.0

True

In [13]:
2 >= 2.01

False

In [14]:
2 <= 2.01

True

In [15]:
2 <= 3 < 4

True

In [16]:
4 <= 7 < 4

False

In [17]:
import numpy as np
import pandas as pd

In [ ]:
(1, 2) == (1.0, 2.0)

True

In [20]:
(1, 2) == (1.0, 2.1)

False

In [19]:
(1, 2) == [1.0, 2.0]

False

In [21]:
(1, 2) == (1.0, 2.0, 1)

False

In [22]:
(1, 2) <= (1.0, 2.0, 1)

True

In [26]:
(1, 2) == (1.0, 2.0, 1)

False

In [37]:
lista_3 = [1, 2, 3]
lista_2 = [1, 2, 3]
lista_3 == lista_2

True

In [41]:
{'a': 1}.values() == {'a': 1}.values()

False

In [42]:
'a' <= 'b'

True

In [47]:
## media, dp, número de elementos
np.random.normal(0, 1, 10)

array([-0.06711123, -0.09161925,  0.0139321 ,  0.40006977,  0.31069423,
       -0.14323926,  0.39959326,  0.65571501,  1.9944295 ,  1.32928356])

In [48]:
np.random.normal(0, 1, 1_000).reshape(10, -1)

array([[-7.63188656e-01,  1.39384575e-01, -3.14643405e-01,
         1.69010504e+00,  3.90595728e-01, -1.63574975e-02,
        -1.12073617e-01, -1.69800065e-01, -5.41265360e-01,
        -6.93930687e-01, -1.25435612e+00,  1.13949772e+00,
         7.93626078e-01,  1.14639135e-01,  6.24169194e-01,
        -1.42076131e-01,  2.95752555e-01, -5.80116575e-01,
         1.01530975e+00,  5.04249196e-01,  8.90009627e-01,
        -1.79402974e-01, -1.27862326e+00,  3.59107141e-01,
         2.67105706e+00,  1.32874250e-01,  1.40077745e+00,
        -2.59198852e-01, -8.68850624e-01,  1.29189488e+00,
         1.54677700e+00, -1.94292326e-01, -5.68840335e-01,
         1.17918595e+00, -5.17440708e-01,  1.95510430e+00,
         9.59183366e-02,  5.00306327e-01, -1.05310680e-02,
         1.43760423e-01,  8.08499766e-01, -1.60918101e+00,
         3.36614569e-01,  1.37667670e+00, -9.22992420e-01,
        -1.73817610e+00,  5.62640876e-01, -1.26679781e+00,
         4.66116194e-01, -1.32710969e+00, -2.11804527e+00,
        -3.18475881e-02, -1.34530584e+00, -2.38227508e-01,
         7.19253509e-01,  6.87065246e-01,  9.00531849e-01,
        -1.86025539e+00,  8.79908670e-02, -1.99815055e-01,
         1.12967301e+00,  2.19019802e-01,  2.87782485e-01,
         8.82435969e-01, -2.56781424e-01, -2.33996350e+00,
        -7.85447938e-01,  5.09908991e-01, -2.38016198e-01,
        -2.21371279e-01,  4.40535308e-01, -3.77319279e-01,
         9.81177989e-01,  3.19407357e-01,  7.99902424e-01,
        -1.87636326e+00,  1.30697475e-01, -9.80243195e-01,
         8.84152560e-02,  7.07095594e-02,  8.25856658e-01,
        -3.56864147e-01,  5.44445159e-01, -1.67729361e-01,
        -1.01656719e+00,  8.36070097e-01, -5.68226519e-01,
        -9.28358752e-01, -2.21811492e+00, -8.40630562e-01,
         3.06735947e-01, -1.30440389e+00,  1.00681569e+00,
        -2.19156688e-02,  9.49909644e-01,  3.41684152e-01,
        -3.02925698e-01, -6.57747970e-01, -3.68135425e-01,
         1.09224225e-01],
       [ 6.72147050e-01, -7.58707804e-01,  1.45436502e-01,
         1.30908099e+00,  1.59275461e+00,  1.59460132e-01,
        -3.65230545e-01, -2.16274773e+00, -1.18501619e-01,
        -5.73996569e-01, -1.09116346e+00, -6.06082744e-01,
        -4.56839284e-01, -1.30570239e+00, -6.94807129e-01,
        -1.02770760e+00,  1.58470369e+00, -5.75533221e-01,
         9.49397893e-01,  8.18907070e-01, -2.35860269e+00,
         3.84823654e-01, -7.44638838e-01, -9.86655103e-01,
         2.63852792e-01,  3.18510123e-01,  1.93540751e+00,
        -7.62187002e-01,  1.44907857e+00, -9.88354207e-01,
         7.95629861e-01,  6.27502038e-02,  5.52293014e-01,
         6.75346466e-01,  6.90718555e-01,  4.24912227e-01,
         3.35525085e-01, -1.18699553e+00,  2.01594947e+00,
        -6.26841255e-01,  4.75120017e-01, -2.18795197e-01,
         2.78847635e-01,  3.55075771e-01, -2.59272526e-03,
         2.11578716e+00,  9.06665686e-01,  1.57234090e+00,
        -1.12147831e+00, -6.98778802e-02,  7.02751232e-02,
         9.22433657e-01, -1.09620964e+00, -1.11964598e+00,
         3.72128838e-01, -1.43489451e+00,  6.65858751e-01,
         6.76002794e-02,  5.74177568e-01,  1.87107663e-01,
         7.89787150e-01,  3.39610987e-01, -3.62974226e-01,
        -1.01463678e+00, -2.71568388e-01, -8.26682503e-01,
         8.17793015e-01,  8.06129938e-01, -7.01769615e-01,
        -3.56104621e-01, -8.03888839e-01,  8.42279732e-01,
        -1.41411443e+00, -1.98056945e+00, -1.11059775e+00,
        -1.30365359e+00,  1.27245417e+00, -1.08067552e+00,
        -9.48212503e-01, -3.36584318e-02,  8.56175595e-01,
         8.67211702e-01, -4.09242578e-02, -2.01463621e-01,
         7.06100299e-01, -4.93862859e-01, -2.68082285e-01,
         7.68666249e-01,  1.66070336e+00,  4.62608249e-01,
        -5.94243631e-01, -6.63134314e-01, -3.83185487e-01,
        -1.46936115e+00, -4.77993408e-01, -1.68316754e+00,
         6.36620675e-01, -1.93484201e-01,  4.08476154e-01,
        -1.29099925e+00],
       [ 6.96661762e-01,  1.73989972e+00,  1.47160979e-01,
         6.99662412e-01,  1.53445812e+00,  1.73123589e+00,
        -1.02101975e-01,  1.16882049e+00,  6.24312712e-01,
         8.71180211e-01, -1.31814718e+00,  1.11748810e+00,
        -1.34905740e+00,  2.47813924e+00, -1.55676087e+00,
         8.78702071e-01, -5.76712170e-01,  1.39727181e+00,
        -1.73552182e+00, -1.39753227e+00, -1.19503346e+00,
         1.88179700e+00, -6.50780258e-01,  9.14252175e-01,
        -2.50671801e-01, -7.62806210e-01,  5.56369968e-01,
         3.15100959e-01,  1.24604292e+00, -3.60861217e-01,
         1.01426629e+00,  2.33475768e-02,  1.69071396e+00,
        -2.15998749e+00, -7.10606209e-01,  1.56181551e-01,
        -2.01326716e-01,  7.38549453e-01, -1.13811704e+00,
        -2.13109130e-01,  3.29740082e-01, -2.20096779e+00,
         7.84019445e-01, -3.93864265e-01,  6.98963688e-01,
         9.92267899e-02, -7.95637516e-02, -3.13825744e+00,
        -5.30658728e-02,  2.20436515e-01,  5.04756781e-01,
        -1.75143816e-01,  4.38127261e-01,  4.42068284e-01,
         1.63505573e+00, -2.71428678e-01, -6.18909716e-01,
         4.19187038e-01, -6.94834342e-01, -8.77569085e-01,
         8.12268688e-01, -6.58552218e-01,  1.15589085e-01,
        -7.79962895e-01, -4.56682241e-01, -8.18103273e-01,
        -7.35851385e-01,  4.89258445e-01,  1.01703587e+00,
        -6.03852232e-01, -6.05613621e-01,  1.05722467e+00,
        -8.39904876e-02,  2.13308764e+00,  4.77841480e-01,
        -3.99189937e-01,  1.15421340e+00, -6.62770313e-01,
         4.94607211e-01,  1.48953025e+00, -1.62833615e+00,
         7.60321605e-04, -8.79001336e-01, -1.04919238e+00,
        -1.10867824e+00, -1.20655993e+00, -4.36350335e-01,
        -3.76101944e-01, -7.24427541e-01,  2.04089992e-02,
         1.01774109e+00,  1.66565431e-01, -1.24585611e+00,
         1.70152808e-01,  7.50794955e-01, -2.56064306e-01,
         7.24223807e-01,  4.99266748e-01,  4.04048465e-02,
        -7.78081454e-02],
       [ 1.05667369e+00, -2.43088301e-01, -8.70263071e-01,
        -5.30760089e-01, -1.61056902e+00,  4.35302486e-01,
        -3.92261894e-01, -7.46338581e-01, -1.22771261e+00,
        -3.94656340e-02,  2.97761846e-02,  6.23049179e-01,
        -6.43065629e-01,  3.65804089e-01,  8.84259538e-01,
        -4.33876602e-01, -1.86455951e+00,  3.58711560e-01,
         3.96608759e-01, -5.14919170e-01,  2.37934623e+00,
        -1.26014076e+00, -5.04816290e-01, -8.04280881e-02,
         4.84143253e-01, -7.58257381e-01,  5.03386725e-01,
         1.12911699e+00, -1.03994025e+00,  9.05375536e-01,
         1.48381595e+00,  1.61098173e+00, -1.15045702e+00,
        -1.97454254e-01,  2.72801104e-01,  7.87560484e-01,
        -1.09671630e+00,  1.39002626e+00, -1.86464711e+00,
        -1.54154513e-01,  4.40217899e-01,  9.26541200e-01,
         9.91717267e-01, -9.82160574e-01, -2.11878614e-01,
        -5.64851957e-01,  3.01396912e-01, -9.93273075e-01,
        -1.37226201e+00, -2.06919892e-01,  8.85196975e-01,
        -1.89761105e+00,  7.02645785e-02, -8.38607108e-01,
        -1.78681017e-01, -9.64180572e-01,  2.66616566e+00,
         1.01222645e+00,  1.05533480e-01,  1.24624615e+00,
         9.15249649e-01, -1.53561847e+00,  5.03626777e-01,
         9.45263853e-01, -2.63189400e+00, -6.14852478e-01,
         5.76856609e-01,  5.10878710e-01, -1.17989086e+00,
         2.61714503e-01,  2.04577160e-01,  1.23161467e-01,
        -1.97960778e+00, -1.05966521e+00, -3.16399737e-01,
        -9.24712665e-01,  3.71847416e-01,  3.95641248e-01,
        -4.87220688e-01, -2.56184691e-01,  1.57606795e+00,
         1.68930535e+00,  1.17874444e+00,  6.11816227e-02,
         1.33950336e-01, -4.75836256e-01, -8.55033612e-02,
        -1.15410100e+00, -4.07708226e-01,  7.60028048e-01,
         5.49472142e-01,  2.25459783e+00,  9.94122920e-01,
         2.57350316e-01,  2.96999372e-01, -2.93438699e-01,
        -9.52062772e-01, -1.26544624e-02, -1.29684118e+00,
        -2.47769160e-01],
       [-3.91711620e-01, -1.32499197e+00,  4.98382548e-01,
        -6.50574717e-01, -2.41664378e-01,  6.41851650e-02,
        -1.20239182e-01,  2.25772473e-01,  2.32902536e-01,
         1.59871082e-02,  2.79822069e+00, -2.54222573e-01,
         1.12179524e+00,  1.09998796e+00, -2.49830259e+00,
         1.23009356e-01,  1.02284193e+00, -7.82246837e-01,
         1.36180224e-01,  5.41651753e-01,  1.35975797e-01,
         4.46973256e-01,  1.54687156e+00,  1.14551207e+00,
         1.30248113e+00, -5.32323919e-01,  3.26909463e-02,
         5.98885907e-01,  2.65521938e-01, -1.39830202e-01,
        -1.03452364e+00, -2.77159385e+00, -1.19489919e+00,
         3.31670983e-02, -1.02248024e+00, -3.02579748e+00,
        -5.42974067e-01,  8.31094025e-01, -5.55660446e-01,
        -2.40170550e-02,  2.79691693e-01,  1.03650848e+00,
         2.09066279e+00,  9.21886296e-01,  6.10975907e-01,
         3.03969081e-03,  8.30043020e-01, -1.25521225e+00,
        -4.03417390e-01, -9.98431250e-01,  4.22912151e-01,
        -1.72631591e+00,  6.43648180e-01,  1.19352217e+00,
         5.15849874e-01,  5.19563466e-01,  7.27675174e-01,
        -2.09076480e+00,  1.27688256e+00, -7.41225753e-01,
         7.54281643e-01,  1.17595738e+00, -7.42059965e-01,
        -4.72723708e-01,  6.22417259e-01,  7.70136529e-01,
         7.28076838e-01, -9.89650190e-01, -1.41104922e+00,
        -1.29750842e-01, -8.42147177e-01, -2.20009490e-01,
        -1.80258192e-01, -4.76750942e-01,  4.88701670e-01,
        -1.31911598e+00,  1.02915209e+00,  1.10174858e+00,
         4.96314157e-01, -1.77350103e-01,  2.53683636e-01,
        -9.96360432e-01, -1.84063474e+00, -8.98292995e-02,
        -9.62947545e-01, -4.65317831e-02,  1.43574062e+00,
         5.80143926e-01,  1.02680024e+00, -4.14205603e-01,
        -9.77571586e-01, -1.52194311e+00,  1.81221657e-01,
         7.87210626e-01,  6.86543414e-01,  1.25154559e+00,
        -7.57871556e-01, -1.37394305e+00,  1.79819419e+00,
         9.80529536e-02],
       [ 1.40693736e-01,  1.21097715e+00,  6.61337042e-01,
         1.69055806e-01,  7.73106408e-02, -2.39160403e-01,
         1.36799448e+00,  6.73270231e-03,  9.10515708e-01,
        -6.47682103e-01,  1.05150974e+00,  1.26595274e+00,
        -1.32872696e+00,  1.89492370e+00,  7.40049164e-01,
        -5.30911516e-01,  1.24917481e-03, -9.16383001e-01,
        -5.63459507e-01,  2.30219891e-01,  6.53085360e-01,
         9.14718376e-02, -1.96719170e+00, -6.60885664e-01,
        -2.37565246e+00, -6.51060213e-01, -1.22131873e+00,
        -8.73480358e-01, -1.81996666e+00,  1.28281268e+00,
         1.72042010e+00, -5.09323890e-01, -2.56901894e+00,
        -4.31600729e-01,  8.37846997e-01, -5.41950235e-01,
        -4.17634724e-01, -4.50175044e-01,  5.18056406e-01,
        -3.76011732e-02,  7.01255897e-01,  7.38484193e-01,
         1.14078537e+00,  8.48332812e-02,  4.42920006e-02,
        -9.49228570e-02, -6.19020467e-01,  6.95474311e-01,
        -3.97002596e-01,  3.28397452e-01,  1.13157913e+00,
         3.69822877e+00, -8.03417284e-01, -1.20385142e+00,
        -3.00772791e-01,  5.28367126e-01, -1.78177979e+00,
        -1.85299593e+00, -5.28877766e-01, -1.17448544e+00,
        -1.97143426e-01,  5.82764619e-01, -1.36613753e+00,
         3.11622414e-01,  2.33585206e-01,  3.52992096e-01,
         6.19708147e-01,  8.71460798e-03, -2.12929299e-01,
         7.91750531e-01,  6.25197595e-02,  1.87460495e+00,
         2.21827656e-01, -2.04447980e+00,  5.00830085e-01,
         1.03989530e+00, -8.14207820e-02,  8.37051303e-01,
        -8.48084660e-01, -1.41617172e-01, -1.54514918e+00,
        -8.19687240e-01,  8.83439730e-02,  6.93240299e-01,
         8.62700720e-02, -1.55782878e-01, -8.62931593e-01,
        -2.39380684e+00, -6.35122477e-01,  5.39551312e-01,
         1.09166215e+00,  2.23069471e-01, -5.34715357e-01,
        -1.19357760e+00,  4.12572755e-01, -1.44152772e+00,
         1.59283926e+00, -1.47227443e+00, -2.13845749e+00,
        -1.94139224e-01],
       [-1.10781327e+00,  3.91729499e-01, -1.39471644e+00,
         5.29635101e-02,  1.17338689e+00, -1.40164447e+00,
         7.34337360e-01,  7.24048435e-02, -6.73948676e-01,
        -4.52148937e-02, -1.20322238e+00,  1.53190215e-01,
         1.10024315e-01, -1.03634722e+00, -2.39702889e+00,
        -2.25461752e+00, -1.01793222e+00,  8.31245123e-01,
         1.55811762e-01, -1.21078037e+00, -5.62439750e-01,
        -3.59958808e-01,  8.46303917e-01,  4.42649383e-01,
        -1.72923643e+00,  5.26219492e-01, -4.20251370e-01,
         5.79333499e-01,  5.20401103e-01, -8.15475125e-01,
        -1.46102350e+00,  3.26307639e-01,  1.72454039e-01,
         4.78896205e-01, -2.37613330e-01, -8.49524756e-01,
         6.37664646e-01, -7.15572854e-01,  2.16173240e+00,
        -6.73201376e-01, -2.93733222e-01,  1.12415160e+00,
        -9.42585663e-01, -6.49913182e-01,  1.87419152e-01,
        -9.05348794e-01,  1.46273461e+00, -8.93341739e-01,
         2.13571952e+00,  9.94948293e-01,  8.01477782e-01,
        -2.01718277e-01,  8.81484437e-01,  9.14100257e-01,
         1.97285460e-01, -6.90755579e-01, -7.49880451e-01,
        -6.05439014e-01, -3.15423102e-01,  3.91913480e-01,
        -1.32873697e+00,  9.66884383e-01, -5.04145727e-01,
         8.72479220e-02,  1.72905501e+00,  9.21056185e-01,
        -1.32500167e+00,  1.17526433e+00, -2.76462275e-01,
        -2.59302589e+00,  7.97178539e-01, -8.33592989e-01,
        -2.38078615e-01,  2.61913963e-01,  5.59823585e-02,
         7.40168648e-01, -1.85255856e+00, -2.63408109e-01,
        -1.60109586e+00,  1.07209160e+00,  4.58516545e-01,
         2.11459719e-01,  2.74439942e+00,  8.02110916e-01,
        -9.52245211e-01, -1.51430978e+00, -4.97688217e-01,
        -2.03883079e-01,  1.22106889e+00,  1.06433510e+00,
         2.57238001e-02, -1.57846678e+00, -6.44333137e-01,
        -1.87606756e-01,  1.74016625e-01,  2.06482319e+00,
        -7.72560138e-01, -1.51728620e+00,  1.08882701e+00,
         2.62330527e-01],
       [ 1.48110973e+00,  6.83273718e-01, -7.89392553e-01,
         6.66068684e-01,  9.70998089e-01,  6.94642993e-02,
         2.05335230e+00, -2.21566275e+00,  1.30461204e+00,
        -5.96872909e-01, -2.56807451e-01,  4.97099133e-01,
         5.56133402e-01, -4.68920129e-01,  6.23966653e-01,
         1.47329189e+00, -9.63084939e-01,  1.92653628e-01,
        -4.59555936e-01, -1.64297434e-01, -1.37160643e+00,
        -1.42032265e+00, -2.24289389e+00,  9.45231507e-01,
        -1.60680685e+00,  1.93481461e+00, -1.24327656e+00,
         9.88022649e-01,  6.43687371e-01,  2.34428094e+00,
         1.78784851e+00,  8.03729696e-01, -2.83888415e-02,
        -1.41858499e+00,  6.98793216e-01, -2.40106158e+00,
         8.62083516e-01, -1.12227462e+00, -2.36036643e-01,
        -1.53391544e+00,  1.77618956e-01, -2.47511588e+00,
         6.90444105e-01,  1.56821259e-01, -1.16544024e+00,
        -1.08271964e+00, -1.78962977e-01, -1.09121654e+00,
        -1.84463018e+00, -8.09904175e-01, -5.20274679e-01,
        -1.61048827e+00, -4.30073844e-01,  3.39292119e-01,
        -1.98544170e+00,  9.71250627e-01,  4.44972669e-01,
         9.88948398e-01, -8.92112220e-01,  5.91785142e-01,
         5.44115254e-01, -4.30996634e-02, -6.68893199e-02,
        -1.57056404e+00,  1.20821587e+00, -1.19268991e+00,
         3.01569786e+00,  1.47390502e+00, -1.98971780e+00,
         5.58847373e-01, -2.48159140e-01,  2.35841262e-01,
         1.66472215e+00, -1.37934287e-01,  5.83397770e-01,
         3.33575966e-01,  6.59562781e-01, -7.76495116e-01,
        -1.13400263e+00,  1.70945430e-01, -6.75239914e-02,
        -8.45956599e-01, -1.57167259e-01,  2.30871160e-01,
        -4.35111935e-01,  1.31902953e+00,  1.62413876e+00,
        -5.31991465e-01,  1.03936396e+00,  1.24258135e+00,
         1.13295076e+00,  6.71240649e-01, -2.73123775e-01,
         9.46659682e-01,  1.69721836e-01,  1.00921677e-01,
         3.87687961e-01,  4.49019381e-01,  2.09575367e+00,
        -1.07048691e+00],
       [-1.24389823e+00,  9.88080765e-01,  7.66326885e-01,
        -1.13723172e+00,  7.73917777e-01, -5.68286151e-01,
         9.82150548e-01, -4.86991998e-01,  5.29021427e-01,
        -2.24114246e-01,  1.22324533e-01,  1.93349667e-01,
        -5.04761843e-01, -4.12798007e-01,  8.04703316e-01,
         1.35652678e+00,  1.43394994e+00, -1.55016862e+00,
         1.23864827e+00,  4.05353415e-02, -5.15680691e-01,
         1.11958126e+00, -5.96781758e-01,  3.55739057e-01,
         7.24955453e-02, -1.22153353e+00,  1.40853977e+00,
         4.28388085e-01, -1.14874743e+00,  9.49835340e-01,
        -1.32789914e+00,  1.91490860e-01,  1.37063185e+00,
         1.44967497e+00, -2.09494958e+00, -9.82964931e-01,
         1.07874684e+00, -5.96719075e-01,  1.15741775e-01,
        -1.16273561e-01,  8.82078503e-02, -7.77770029e-01,
         1.67641810e+00, -1.50853954e+00,  7.34317043e-01,
         1.06945240e+00,  1.12585709e+00,  1.33626023e+00,
        -8.44801500e-01, -9.43308254e-01,  1.48507335e+00,
         6.85976800e-01,  1.06110668e+00,  2.16769341e+00,
         6.34824370e-01, -4.81774998e-01,  8.70561481e-01,
        -1.25083198e+00, -1.17015522e-01,  3.66986280e-01,
        -7.92551659e-01, -3.21355078e-01, -1.27472272e+00,
         2.57277380e+00,  1.58644200e+00, -2.53323005e+00,
         1.07468702e-01, -1.26092327e+00, -1.20720097e+00,
        -1.05973795e-01, -4.16093540e-01, -7.65108397e-01,
        -7.11413111e-01, -9.07561908e-01,  6.78584658e-01,
        -1.30668482e+00,  4.89032266e-01,  9.02980426e-01,
        -9.27431532e-01, -1.23700391e+00, -1.79864111e-01,
         1.55147341e+00, -2.13306830e-02,  7.64736551e-01,
         8.35421278e-01,  1.12674505e+00,  1.20443561e+00,
        -1.84308076e+00, -6.73639169e-01,  1.37671558e+00,
         4.61891530e-01,  2.23010899e+00,  9.96980432e-01,
        -5.36661397e-01, -1.18157686e+00,  4.79400096e-02,
         8.32969049e-01,  8.83844301e-01, -7.34227428e-01,
        -1.03796024e+00],
       [-7.34914160e-01, -1.79953688e-01,  5.16412911e-02,
         1.70201731e-02,  2.28120016e+00,  1.16976773e+00,
         8.26202521e-01, -3.27268495e-01, -1.38841819e+00,
         1.29031245e+00,  5.58147378e-01, -9.13206453e-01,
         9.69505004e-01,  1.03796612e+00, -3.01941434e-01,
        -1.04533699e-01, -7.74282149e-01, -4.47761073e-01,
         8.84546548e-01, -9.01965951e-02, -9.93816693e-01,
        -4.63193401e-01,  1.86777459e+00, -2.00679774e-01,
         9.76293882e-01,  2.78152928e-01,  3.32159136e-01,
        -2.06860703e-01,  1.92240058e-01, -2.25339008e+00,
         1.82740679e+00,  7.90204783e-02,  8.66098590e-01,
        -5.56845535e-01, -2.74902767e-01, -5.88693970e-01,
        -8.11544508e-01, -2.06364919e-01, -2.97269235e-01,
         3.76008792e-01,  4.81101386e-01, -3.56708118e-01,
        -9.45069437e-01, -3.12152817e-01,  1.35453657e+00,
         4.55582349e-01,  1.30883532e-01, -6.01666110e-01,
        -7.57130643e-01, -1.42070591e+00, -1.28333925e-01,
         4.01975832e-01, -3.43677466e-01,  4.04109919e-01,
        -5.17945929e-01, -9.85265158e-01,  9.64316939e-01,
        -2.05955601e-01, -5.76612237e-02, -1.09974273e-01,
         3.52759038e-01,  4.02575881e-01,  8.85442803e-01,
         1.11076842e+00,  6.86333112e-01,  1.14686833e+00,
         1.46131623e+00, -2.84633423e-01,  2.18678813e-01,
        -2.10197059e-01, -4.88208071e-01,  1.33522111e+00,
        -1.05547544e+00, -8.22003581e-02,  2.27377176e+00,
         8.15165287e-01, -9.23469979e-01, -7.31305125e-01,
         6.18622532e-01,  9.35745414e-01,  2.61754930e+00,
        -3.92525695e-02,  7.93988371e-01,  2.73517936e-01,
         1.52441482e+00, -2.19311152e-01,  8.34223759e-01,
        -4.10966198e-01, -1.78737033e+00,  2.30313873e-01,
         9.45982792e-01, -1.95103548e-01, -6.06140825e-01,
         1.02434241e+00, -1.91185311e+00, -2.42861307e-01,
        -3.60858472e-01, -2.27427389e-01,  5.12920646e-01,
         1.08220577e+00]])

In [51]:
array = np.random.normal(0, 1, 1_000).reshape(-1, 10)
array [:2]

array([[-0.42387928,  0.3172505 ,  2.06625609,  0.49086854,  0.27687927,
        -0.42696953, -0.05804336,  1.68216674, -0.39410915, -0.09313091],
       [-0.95677699,  1.83266522,  0.615069  ,  1.16651284,  0.04688873,
         0.60683651, -0.46624915, -0.15882596, -0.34413607,  1.16225009]])

In [52]:
array_1 = array = np.random.normal(0, 1, 1_000).reshape(-1, 10)
array_2 = array = np.random.normal(0, 1, 1_000).reshape(-1, 10)
array_1 [:2]

array([[-1.64172635, -0.45343257,  1.75127913, -0.96607899,  1.87384942,
        -0.23271443, -1.13136501,  0.35783934,  1.6125271 ,  1.01007235],
       [-0.5464784 , -0.64398716,  0.26280161, -2.16999515,  0.45679299,
         0.33617127,  0.85666591,  0.48383136, -0.20447714, -1.27661436]])

In [53]:
array_1 == array_2

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [58]:
## conjunto de dados aleatórios iguais
np.random.seed(42)
array_1 = array = np.random.normal(0, 1, 1_000).reshape(-1, 10)
array_2 = array = np.random.normal(0, 1, 1_000).reshape(-1, 10)
print(array_1[:1])
print(array_2[:1])

[[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696
   1.57921282  0.76743473 -0.46947439  0.54256004]]
[[ 1.39935544  0.92463368  0.05963037 -0.64693678  0.69822331  0.39348539
   0.89519322  0.6351718   1.04955272 -0.53523521]]

In [57]:
array_1 == array_2

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [59]:
pd.DataFrame(array_1) <= pd.DataFrame(array_2)

        0      1      2      3      4      5      6      7      8      9
0    True   True  False  False   True   True  False  False   True  False
1    True   True   True   True   True   True   True  False   True   True
2   False  False  False   True   True   True   True  False   True  False
3    True  False   True   True  False   True  False   True   True   True
4    True  False   True   True   True   True   True  False   True   True
..    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
95  False   True   True  False  False   True  False   True   True  False
96  False  False   True  False   True  False   True  False  False   True
97   True  False  False   True   True   True   True   True   True  False
98  False  False   True   True   True   True  False  False  False   True
99   True   True   True   True   True   True  False  False   True  False

[100 rows x 10 columns]

In [60]:
filtro_array = array_1 <= array_2
filtro_array[:2]

array([[ True,  True, False, False,  True,  True, False, False,  True,
        False],
       [ True,  True,  True,  True,  True,  True,  True, False,  True,
         True]])

In [61]:
df_1 = pd.DataFrame(array_1)
df_2 = pd.DataFrame(array_2)
df_1.head()

,0,1,2,3,4,5,6,7,8,9
0,0.496714,-0.138264,0.647689,1.523030,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.542560
1,-0.463418,-0.465730,0.241962,-1.913280,-1.724918,-0.562288,-1.012831,0.314247,-0.908024,-1.412304
2,1.465649,-0.225776,0.067528,-1.424748,-0.544383,0.110923,-1.150994,0.375698,-0.600639,-0.291694
3,-0.601707,1.852278,-0.013497,-1.057711,0.822545,-1.220844,0.208864,-1.959670,-1.328186,0.196861
4,0.738467,0.171368,-0.115648,-0.301104,-1.478522,-0.719844,-0.460639,1.057122,0.343618,-1.763040

In [62]:
df_1[filtro_array].head()

,0,1,2,3,4,5,6,7,8,9
0,0.496714,-0.138264,0.647689,1.52303,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.54256
0,0.496714,-0.138264,0.647689,1.52303,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.54256
0,0.496714,-0.138264,0.647689,1.52303,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.54256
0,0.496714,-0.138264,0.647689,1.52303,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.54256
0,0.496714,-0.138264,0.647689,1.52303,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.54256